### PR TITLE
fir for broken js file inclusion

### LINKED ISSUE #213: Plugin breaks in Build >1.0.469
Because this plugin abuses an unsupported bug in older October builds (loading JS files as partials) that was blocked for security reasons in Build v1.0.469 and onwards (and never should have been present in the first place) this plugin breaks on newer builds of October. See https://github.com/octobercms/october/issues/5272.

The problematic code is here: https://github.com/skydiver/october-plugin-forms/blob/f3fe2feca89712a7be2c4758c4e5c12d39c0369b/classes/MagicForm.php#L278-L283

### PR DESCRIPTION
**Pull request by mjauvin**
apply fix suggested by Samuel Georges (@daftspunk)

fixes #213

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin I don't know if this will work because it doesn't evaluate the twig. You should be able to just rename the files to have .htm extensions though

**Comment by mjauvin** [comment]
You're right.

**Comment by skydiver** [comment]
@LukeTowers and @mjauvin 

it's not enough to load a plain html with all the javascript code inside a `<script></script>` tag?

**Comment by LukeTowers** [comment]
@skydiver What do you mean?

**Comment by skydiver** [comment]
> @skydiver What do you mean?

for the reset form feature, we are loading `components/partials/js/reset-form.js` which is just a line of javascript
```
$('{{ id }}').parents('form')[0].reset();
```

we can turn into an html file with the following content:

```
<script>
$('{{ id }}').parents('form')[0].reset();
</script>
```

same will apply for the remaining js files

**Pull request merged**
