### PR TITLE
Add support for translations.

### PR DESCRIPTION
**Pull request by mariavilaro**
Add support for translations (Issue #15 ). If Translate plugin is available, it looks for the translated messages. If the messages don't exist, they will be available after the next scan for messages in the Translate plugin

### CODE REVIEW

**Comment by skydiver** [comment]
Hello @mariavilaro, can you explain me how this works?
I don't have too much experience with the translate plugin.

Thanks.-

**Comment by mariavilaro** [comment]
With the translate plugin you can use multilingual texts with this twig filter:

{{ 'text to translate'|_ }}

The first time that this is called, it creates a message in the default language that then you can translate to the other enabled languages from the translate plugin settings > messages. The next times it is called it will just show the message in the active language. If you don't translate it, it will show the default language text (in this case "text to translate"}.

So my code does the same: it checks if the translate classes exit, and then creates the messages the first time they are called, if they exist it loads them. So you have to:

- configure the form component success and error texts (and validation errors); then send one time the form correctly filled so it gives the success message, and another one with bad data so it gives the error message; and finally go to the translate plugin messages: the texts will be there so you can translate them as you wish

Maybe it would be better if the messages are created without needing to send the form 2 times, preloading the messages when the component properties are saved or something like this, but I don't really know how to do it, I don't have too much experience with components.

**Comment by skydiver** [comment]
Sorry @mariavilaro, i can't make it work.

Your instructions are clear, but for some reason my messages doesn't get translated.

Can you attach your theme so i can see component properties and why doesn't work for me?


Thanks.-

**Comment by mariavilaro** [comment]
Hi! sorry could not manage to get back to you sooner. Did you manage to make it work?

**Pull request merged**
